# Generated by Django 3.1.1 on 2020-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(max_length=200, null=True, default = 0),
        ),
    ]
