# Generated by Django 3.1.1 on 2020-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_article_good_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(default='', upload_to='', null=True),
        ),
    ]
