# Generated by Django 3.1.1 on 2020-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_article_good_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
