# Generated by Django 3.1.1 on 2020-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
